### ISSUE TITLE
Fails to deploy

### ISSUE THREAD

**Issue by Wolfyxon** [fl0zone/template-nodejs#5]
When I deploy the app in fl0, it waits around 4 minutes then shows this:
```
Rollout
Status: FailedToProgress
Status Message: ProgressDeadlineExceeded
Status Reason: ReplicaSet "a5ff6288f-fbd7-49ad-b24f-95167364195f-55fdbb498f" has timed out progressing.
Total Replicas: 2
Healthy Replicas: 0
Last Update Time: 2023-10-19T19:35:31+00:00
```
The port is set to 8080 (default) in fl0 environment vars.

**Comment by Wolfyxon** [comment]
Hmm removing this section from `app.js` made the site accessible in a browser through the URL and the logs now show up but it still shows it as "failed" 
```js
app.get('*', (req, res) => {
    res.redirect('/');
})
```

**Comment by stennie** [comment]
Hi @Wolfyxon!

Apologies this issue did not get an earlier response. Questions for this repo are generally expected to be feedback about the application template rather than more time-sensitive questions specific to a deployment.

I hope you were able to resolve your deployment problem. It looks like there was an issue with your deployment not responding to a health check on the expected port, leading to a timeout during the [deploy stage](https://docs.fl0.com/docs/troubleshooting#deploy-stage).

For general help with FL0 deployment questions, please join the [FL0 Community & Support Discord](https://discord.gg/QPXqWK3bVw).

Regards,
Stennie

**Comment by Wolfyxon** [comment]
The issue was about this template. I used this exact application and it was failing to deploy.
